name: Run Python unit tests

on:
  workflow_call

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.11', '3.12' ]
      fail-fast: false

    steps:
      - name: Checkout earthdata-hashdiff repository
        uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r tests/test_requirements.txt

      - name: Make artefact directories
        run: mkdir -p tests/reports tests/coverage

      - name: Run tests
        run:
          pytest --junitxml=tests/reports/earthdata-hashdiff_junit.xml --cov earthdata_hashdiff --cov-report html:tests/coverage --cov-report term

      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: Test results for Python ${{ matrix.python-version }}
          path: tests/reports/earthdata-hashdiff_junit.xml

      - name: Archive coverage report
        uses: actions/upload-artifact@v4
        with:
          name: Coverage report for Python ${{ matrix.python-version }}
          path: tests/coverage/
